Make sure scribe only runs on rc tags

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -78,6 +78,14 @@ jobs:
     needs: [build]
     runs-on: ubuntu-latest
     steps:
+      - name: Check tag format
+        run: |
+          if [[ "${GITHUB_REF}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
+            echo "Tag matches format"
+          else
+            echo "Invalid tag format"
+            exit 1
+          fi
 
       - uses: actions/checkout@v4
 
